# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "main" do |main|
    main.vm.box = "archlinux/archlinux"
    main.vm.network "public_network", use_dhcp_assigned_default_route: true
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/focal64"
    ubuntu.vm.network "public_network", use_dhcp_assigned_default_route: true
  end
  config.vm.define "arch" do |arch|
   arch.vm.box = "archlinux/archlinux"
   arch.vm.network "public_network", use_dhcp_assigned_default_route: true
  end

end
